FROM node:22

# Install Chrome dependencies
RUN apt-get update && apt-get install -y \
    wget \
    ca-certificates \
    fonts-liberation \
    libappindicator3-1 \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libcups2 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libnspr4 \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    xdg-utils \
    libxshmfence1 \
    libgbm1 \
    libxext6 \
    libxfixes3 \
    --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Redis
RUN apt-get update && apt-get install -y redis-server && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Install dependencies
RUN npx puppeteer browsers install chrome

COPY prisma ./prisma/
RUN npx prisma generate --no-engine

# Use production NODE_ENV
ENV NODE_ENV=production

# Install only production dependencies
RUN npm ci --only=production

# Remove dev dependencies and cache
RUN npm cache clean --force && rm -rf /root/.npm

# Copy only necessary files for production
COPY . .

# Expose app port
EXPOSE 5000

# Start Redis in the background, then start the app
CMD service redis-server start && npm start
